stages:
  - deploy
  - destroy

variables:
  TF_API_TOKEN: $TF_API_TOKEN
  TF_STATE_NAME: default
  TF_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/gitlab-org/terraform-images/releases/1.4:v1.0.0"
  SECURE_FILES_DOWNLOAD_PATH: "./"

deploy:
  stage: deploy
  image: ${TF_IMAGE}
  before_script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | sh
  script:
    - echo "$juankeys" > juankeys.pem
    - cat juankeys.pem
    - chmod 600 juankeys.pem
    - gitlab-terraform init
    - gitlab-terraform validate
    - gitlab-terraform plan
    - gitlab-terraform plan-json
    - gitlab-terraform apply
    - rm juankeys.pem
  resource_group: ${TF_STATE_NAME}
  cache:
    untracked: true
    paths:
      - /
  only:
    - main

destroy:
  stage: destroy
  image: ${TF_IMAGE}
  when: manual
  before_script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | sh
  script:
    - echo "$juankeys" > juankeys.pem
    - chmod 600 juankeys.pem
    - gitlab-terraform destroy
    - rm juankeys.pem
  resource_group: ${TF_STATE_NAME}
  only:
    - main
